version: '3'

services:
  test:
    build:
      context: .
    command: ["script/test"]

  check-assets:
    build:
      context: .
    environment:
      - RAILS_ENVIRONMENT=production
    command: ["bin/rails", "assets:precompile"]
