version: '3.8'

services:
  test:
    build:
      context: .
    command: ["script/test"]

  check-assets:
    build:
      context: .
    environment:
      - RAILS_ENVIRONMENT=production
    command: ["bin/rails", "assets:precompile"]

  bundled:
    build:
      context: .
      target: bundled
