# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b41312108174066ce5fea3fc0f0b2d7355fbe2bd60d2a8c1593c8774b4f270032d3ede3655417203722c596c7a8e5150f30d93e82e454155b1f4e097134f85

test:
  secret_key_base: 67569a822c752d6d6c2b8ece1e607df4842042dca79d2ecf4c3e311399ed007083decf2c8379df4b2868e6192a6429058bf859bea2c3926246abee5dad6f11e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
