#!/bin/sh
#/ Usage: script/deploy BRANCH

set -e

commit="$1"
if git rev-parse --verify --quiet "${commit}"; then
  # TODO - check CI
  set -x
  docker-compose -f docker-compose.test.yml build --force-rm --quiet check-assets
  docker-compose -f docker-compose.test.yml run --rm check-assets
  git push --force heroku "${commit}:refs/heads/master"
else
  cat "$0" | grep ^#/ | cut -c4-
fi
